//Halfling last names
var HalflingLast = [
    "Amster", "Ashworthy", "Autumntrack", "Bandawax", "Banks", "Bano", "Bilberry", "Blackgrain", "Blebblorbath", "Boffin", "Bolger", "Bracegirdle", "Brandybuck", "Brockhouse", "Brown", "Brownlock", "Brushgather", "Bullroarer", "Bunce", "Burrowes", "Burrows", "Butcher", "Chubb", "Chubb-Baggins", "Clayhanger", "Cloudsworn", "Coldfall", "Cotton", "Dale", "Dalire", "Dayblossom", "Deepworth", "Derwegglo", "Devix", "Dewfoot", "Dudley", "Elvellon", "Esdaebblas", "Faneth", "Farfoot", "Fleetfoot", "Fofflingos", "Freestream", "Galialrird", "Gammidge", "Gamwich", "Gardner", "Gaukrogers", "Glerwolk", "Glosband", "Gluttonbelly", "Gnegglusdox", "Gnendinges", "Goldworthy", "Goodbarrel", "Goodbody", "Goold", "Graybrook", "Greenbottle", "Greenhand", "Greenspan", "Grub", "Hamson", "Hazzarg", "Headstrong", "Heartstream", "Heathertoe", "Hedgehopper", "Highhill", "Hillbrow", "Hilldream", "Hilltopple", "Hogpen", "Hornblower", "Hubrubblu", "Humblegrain", "Ironsworn", "Jallisall", "Kaese", "Kalliwart", "Kilzex", "Leafwalker", "Leagallow", "Lindenbrook", "Lonespark", "Longbottom", "Longfoot", "Longriver", "", "Maggot", "Marmidas", "Melilot", "Milddraft", "Mildvalor", "Millbridge", "Milliciny", "Mistmore", "Montajay", "Moonward", "Mossgrain", "Newtan", "Noakesburrow", "Noldeal", "North-took", "Olas", "Oldfur", "Orgulas", "Ostgood", "Overhill", "Palestream", "Pinda", "Pott", "Proudmead", "Puddifoot", "Quettory", "Richblaze", "Riverflower", "Rivers", "Rolri", "Roper", "Rumble", "Rumblebelly", "Rumblewing", "Sackville", "Salnir", "Sewhaeth", "Shadowbranch", "Shortwick", "Silentfoot", "Silzes", "Sire", "Softblaze", "Springgleam", "Stone", "Stoneglade", "Stoor", "Sure", "Talbot", "Tealeaf", "Telnu", "Thorngage", "Tighfield", "Took", "Tosscobble", "Townsend", "Trill", "Truthmore", "Truthstride", "Underbough", "Underburrow", "Underhill", "Underlake", "Undertree", "Vlavral", "Vlibrusbird", "Vlirdidrerg", "Vusdazzai", "Weatherbee", "Whitsoar", "Ygglox", "Zaragamba"
]

//Elf last names
var ElfLast = [
    "Adanell", "Aelasar", "Aelorothi", "Aendryr", "Aerasumé", "Aeravansel", "Aldaval", "Aloiene", "Alqualonde", "Amaratharr", "Amarthen", "Ammath", "Amrallatha", "Anuaer", "Ardorius", "Artordhron", "Augalvaryl", "Beinion", "Beor", "Braegen", "Briarbosk", "Brightcloak", "Brightsong", "Brightspear", "Brightstar", "Brightwing", "Castien", "Caundur", "Celelaeth", "Cererindur", "Chamaranthe", "Clatharla", "Corellon", "Cormyth", "Coudoarluth", "Craulnober", "Crystalis", "Cubrinmyr", "Darkbrood", "Darkcloak", "Darkwing", "Deryth", "Dor-lomin", "Dragonrider", "Eaglelord", "Ealoloth", "Ealoviel", "Earcorn", "Elaéyadar", "Elassidil", "Elerelwa", "Elian", "Elkenmage", "Ellarian", "Elond", "Erladden", "Erlshade", "Eroth", "Eruien", "Erunonidan", "Estelda", "Evanara", "Faefindas", "Faelen", "Faenion", "Faenor", "Faerondalan", "Felarathael", "Finwe", "Floralei", "Flyleaf", "Frostfang", "", "Gaelen", "Galaalta", "Goldenleaf", "Gourael", "Greencloak", "Gwaelon", "Hadirsyr", "Hador", "Haell", "Haerlgent", "Haleth", "Hasterien", "Hatanar", "Helion", "Hessarion", "Idhtulcdrach", "Ievos", "Iliathorr", "Ilnatar", "Immeril", "Impanton", "Imphenon", "Ipyllasc", "Irian", "Isiliraiellyn", "Kadhorduil", "Kithsidhion", "Kraok", "Laedireil", "Laelithar", "Lannarseer", "Laralytha", "Larbrinlal", "Larenthanil", "Larethian", "Lashrael", "Lassagaseer", "Lasslail", "Leaadion", "Liondale", "Lithelon", "Lithron", "Maedhros", "Maeglin", "Maeir", "Maertel", "Magor", "Maltathdar", "Moondown", "Moonflower", "Moonford", "Moonglade", "Moonshrine", "Moorfly", "Nenaias", "Nhachashaal", "Nhaéslal", "Nharimlur", "Nightstar", "Nightswatch", "Nightwing", "Noldorin", "Norodiir", "Northstar", "Oaktree", "Ongluth", "Orama", "Orbryn", "Quendi", "", "Redwing", "Rhothomir", "Rhuidhen", "Rhyllgallohyr", "Rivleam", "Rivvikyn", "Runemaster", "Sarsantyr", "Selakiir", "Selmer", "Shinestar", "Shiredove", "Silkstream", "Siltral", "Silverbow", "Silverhand", "Silveroak", "Silverspear", "Simserion", "Snowfell", "Snowreign", "Stillhawk", "Stilmyst", "Stormspear", "Straeth", "Strongbow", "Suldusk", "Sunfoal", "Sunshield", "Sunstar", "Sylleth", "Tassarion", "Tathdel", "Taurntyrith", "Telerie", "Tellynnan", "Teshurr", "Thalien", "Thoimion", "Thothiion", "Thundruil", "Tipantdon", "Turnvale", "Tyrell", "Vanamaeduil", "Vanvathar", "Vispasial", "Voronbund", "Vyshaan", "Waelvor", "Werloththar", "Whitethistle", "Windslore", "Windstar", "Windwalker", "Wingglide", "Wintermoon", "Wolfspeak", "Yrauos"
]

//Dragonborn last names
var DragonbornLast = [
    "Crincacmir", "Yalduash", "Uaxal", "Kruamrith", "Kloldrindead", "Creastatorrun", "Clerrhon", "Nyuuldus", "Axor", "Thacodimin", "Voccith", "Numbucmid", "Folmac", "Lualrur", "Amruajad", "Klealkiar", "Klichuuth", "Cralthud", "Temmudak", "Amreashtur", "Foldraankonid", "Krephuarid", "Carek", "Narnajir", "Karrhish", "Certhejaal", "Cechikel", "Ucer", "Yumputhorguun", "Tuaphek", "Dimpeadulus", "Shornash", "Ernanthijar", "Myemrik", "Yelxidak", "Gaarthar", "Myimrin", "Gilxekilluc", "Onxidelith", "Kiphir", "Crancar", "Iccuuc", "Krialras", "Yorthus", "Urrhaan", "Shaammasijic", "Drarnok", "Malxaan", "Kluapor", "Nyombukmul", "Faaldintharrun", "Uuxirirgek", "Maccal", "Mempal", "Unxas", "Tirdunkundak", "Diltheth", "Merdijad", "Kliphith", "Delmokmidoc", "Gamticosh", "Embiacnirgir", "Cemtun", "Nemmiashkmek", "Enxendrek", "Tialtetar", "Axic", "Narjun", "Gearthashkmec", "Dialruc", "Yichojek", "Cloldrajur", "Uardin", "Clecanendek", "Pruncenshtor", "Shuanxur", "Tarrhunthergesh", "Klasteash", "Fildoker", "Ildad", "Irnealas", "Klampad", "Shimpiduk", "Klinxankiar", "Taarrhileallac", "Althadin", "Enkenthuad", "Erostumak", "Sheccac", "Oldak", "Kambun", "Tacaad", "Thaamtekelud", "Dompin", "Tharrhushkmenir", "Claammedamuur", "Craldesuudul", "Dustec", "Kricetol", "Liltutes"
]

//Tiefling last names
var TieflingLast = [
    "Amarzian", "Chalthoum", "Vavrus", "Girgis", "Sedlak", "Eleftheriou", "Rybar", "Massri", "Novak", "Mubarak", "Carnago", "Lanik", "Sawalha", "Janda", "Shehata", "Huba", "Mouggi", "Cerma", "Biljon", "Brada", "Domarien", "Admon", "Bedrich", "Dalkon", "Griswold", "Malfier", "Quentin", "Talfen", "Wolfram", "Navaren", "Iscitan", "Meklan", "Hagar", "Daylen", "Benvolio", "Benak", "Tavon", "Ritter", "Ningyan", "Hamlin", "Meluzan", "Jeras", "Eandro", "Alard", "Adler", "Dirke", "Krynt", "Helmut", "Norris", "Samm", "Menetrian", "Thom", "Alwyn", "Dian", "Leyten", "Milos", "Semil", "Vanan", "Anlow", "Aimery", "Paradas", "Wendell", "Sevenson", "Namen", "Madian", "Dungarth", "Ambert", "Gallus", "Nilus", "Tamond", "Romazi", "Ahren", "Dedric", "Alain", "Nerle", "Alaric", "Falken", "Regdar", "Bram", "Mikal", "Brandis", "Goldrudder", "Kroft", "Shaulfer", "Voortham", "Zethergyll", "Devries", "Silvergraft", "Lamoth", "Sarzan", "Grantham", "Graylock", "Steveren", "Talandro", "Ratley", "Falck", "Dalicarlia", "Coldshore", "Armanci", "Serechor", "", "Danamark", "Fallenbridge", "Redraven", "Targana", "Dyrk", "Wilxes", "Swiller", "Roxley", "Moonridge", "Hayward", "Drumwind", "Ereghast", "Carnavon", "Bilger", "Hindergrass", "Netheridge", "Seratolva", "Towerfall", "Shadowhorn", "Wintermere", "Taran", "Hyden", "Shattermast", "Kreel", "Fletcher", "Cresthill", "Blackstrand", "Arkalis", "Szereban", "Cuttlescar", "Fryft", "Leerstrom", "Stavenger", "Varcona", "Lavant", "Lynchfield", "Stormchapel", "Zatchet", "Torzalan", "Vrye", "Umbermoor", "Oakenheart", "Gullscream", "Pieter", "Iscalon", "Donoghan", "Caskajaro", "Ballard", "Trelenus", "Faringray", "Pyncion", "Raeburn", "Baldric", "Daargen", "Wygarthe", "Varzand", "Revenmar", "Brightwater", "Trevethor", "Coyle", "Tryphon", "Welfer", "Celik", "Gul", "Oyal", "Yilmaz", "Kirca", "Hartman", "Pekkan", "Muhtar", "Vadu", "Erbil", "Aksu", "Kaya", "Sahin", "Gandt", "Baykal", "Ozdemir", "Demir", "Senturk", "Vrago", "Mansur", "Barrelhelm", "Grimtor", "Ramcrown", "Zarkanan", "Hackshield", "Drakantal", "Gomec", "Silvertarn", "Deepmiddens", "Kaplan", "Garkalan", "Polat", "Copperhearth", "Markolak", "Skandalor", "Ambershard", "Rockharvest", "Evermead"
]

//Human & Half-Elf last names
var HumanLast = [
    "Dawnflower", "Glowtide", "Orbshard", "Deadflame", "Leafbone", "Tuskstride", "Hilldew", "Burningsong", "Sharprun", "Ragewater", "Honorwhisper", "Steelcrusher", "Roughsoar", "Rockaxe", "Youngspear", "Mossbasher", "Firehorn", "Monsterflower", "Softwalker", "Lunascar", "Fireforest", "Runesnarl", "Morningspirit", "Doomflayer", "Alpenflaw", "Caskshine", "Flamebraid", "Titanblight", "Regalglory", "Doomsteam", "Wheatdraft", "Mistwinds", "Stonetail", "Sharpshine", "Lionoak", "Tarrenwhisper", "Seadream", "Ironthorn", "Horsebringer", "Moonwillow", "Rumbleglow", "Mirthroar", "Dragonshield", "Morningstrength", "Springswift", "Daywillow", "Keenrider", "Silversword", "Amberscream", "Ashaxe", "Dreamblower", "Roughbone", "Hardstrength", "Twilightsnout", "Woodendreamer", "Simplewound", "Mastertail", "Plainshot", "Covenshaper", "Greenthorn", "Ravendust", "Liontide", "Casktrack", "Axewhirl", "Lionarrow", "Grandheart", "Horsesprinter", "Woodenwater", "Proudstream", "Clawvigor", "Keenlance", "Truthlash", "Deadwater", "Heavyshaper", "Glowbrew", "Hawkhand", "Hammersinger", "Bloodroot", "Dawnspirit", "Daydancer", "Clantrapper", "Axehorn", "Graysplitter", "Solidflayer", "Fogroot", "Redbranch", "Deathbeam", "Softjumper", "Marshhide", "Ragespire", "Barleyhell", "Pyrebone", "Frozenstrider", "Daymane", "Heartkeeper", "Willowbleeder", "Brightfang", "Dawnsky", "Moonfeather", "Voidrock", "Havenchaser", "Hellshadow", "Earthwolf", "Darkeyes", "Deadsprinter", "Clawbash", "Softdreamer", "Whitcaller", "Burningsoar", "Marbletalon", "Seawing", "Farrowbloom", "Creststream", "Mirthwound", "Hallowedhammer", "Bloodvalor", "Shadegrip", "Silentbrook", "Alpengazer", "Sharplance", "Haventalon", "Caskglade", "Dragondane", "Slatedust", "Whitekeep", "Gloomthorn", "Rageforest", "Longgrove", "Flamebrace", "Ironmore", "Blackclaw", "Whitebone", "Sterndane", "Fourlance", "Horsecrest", "Waterhell", "Terraflare", "Ashgleam", "Clawhammer", "Goldlight", "Flamestrike", "Hawkfist", "Mournblade", "Sharpsorrow", "Fourshield", "Pyrehide", "Clearfall", "Twohand", "Fernblower", "Phoenixbough", "Pyrevale", "Gloompike", "Grayshaper", "Stonewolf", "Lightningmourn", "Ravenseeker", "Stillarm", "Coldeyes", "Oatswift", "Sacredstone", "Strongdown", "Twilightgrove", "Noseless", "Mountainspell", "Amberpeak", "Mistshaper", "Hawkstrength", "Dewcrest", "Freewhirl", "Cragbreath", "Runelance", "Mirthwolf", "Featherforge", "Ashwoods", "Grassclaw", "Threecaller", "Burningsoar", "Barleyrider", "Fireoak", "Elfflow", "Redmaul", "Nightscribe", "Wyvernward", "Downrunner", "Greatstrike", "Horsevalor", "Alpensun", "Clanoak", "Stagdream", "Silverdrifter", "Blazesteel", "Skyshaper", "Rageflayer", "Silentmark", "Grizzlydoom", "Greatshield", "Moonglide", "Terrabinder", "Spiritbeard", "Lionshard"
]

//Dwarf last names
var DwarfLast = [
    "The Axebreakers", "The Copperpots", "The Mithril-born", "The Silverbeards", "The Blue Mountain Clan", "The Craghaven Dwarves", "The Ironhelms", "The Craghold Clan", "The Crannog Clan", "The Boatmurdered", "The Alderfists", "The Ashenforge", "The Birchstone", "The Elderbeards", "The Hazelaxes", "The Hollystrak", "The Junipkil", "The Oakenshield", "The Rowangga", "The Willowgart", "The Yewhammer", "The RockRacks", "The StoneBorns", "The HammerPants", "The IronSets", "The Goldbounds", "The CopperTones", "The DarkSeekers", "The ForgeKeepers", "The ShopSweepers", "The BoozeBeards", "The Dûnhark", "The Khazad’amon", "The Golden Dwarves", "The Orcshorn", "The Hafgrey", "The Hafduergar", "The Sky Lords, Riders of Griffons", "The Ramrider", "The Lords of the Gyre Mountains", "The Firebeards", "The Skyminer", "The Kharak’bast", "The Gnarlbeards", "The Quartzeaters", "The McKnuckles", "The Ironjaws", "The SureFoots", "The LongWalkers", "The Sons of Iron", "The EarthChildren", "The Smiths (Pewter Smith, Gold Smith, Gun Smith)", "The Leadbelly", "The Gritsword", "The Goldenbrace", "The Enemyfighters", "The Dirgebane", "The Khag", "The Akurkam", "The Chazakül", "The Grimsleepers", "The Deep-Crag Clan", "The Rockjaw Clan", "The Highcliff Clan", "The Steel Whoole Clan", "The Fissurefisher Clan", "The Dustbuster Clan", "The Mountainhall Clan", "The Spiral Cavern Clan", "The Gravelgut Clan", "The Gritgobbler Clan", "The Spire Forge Clan", "The Totalay Hammard Clan", "The Mountain Homes", "Clan Krakhammer", "Clan Stoneshaft", "Clan Goldtrickle", "The Forgeworn", "The Mountainhewers", "The Thunder Kings", "The Stormhammers", "The Riverwrights", "The Frostbeards", "The Hammerdashers", "The Lords of the Crystal Caverns", "The Goldbrewers", "The Stormpeak", "The Frostpeak", "The Thundershod", "The Hammerkeepers", "The Winterhills", "The Quick-smelter clan", "The Goldenfield Clan", "The Red-potters", "The Highfields", "The Honeywhiskey Clan", "The Blackbones", "The Longbeards", "The Silvertomes", "The Mountainfalls"
]